var bodyElement = document.body;
bodyElement.style.backgroundColor = "#000";
bodyElement.style.color = "#fff";
bodyElement.style.border = "2px solid red";
console.log("body background", bodyElement.style.backgroundColor);
var divElement = document.getElementsByTagName("div");
console.log("divs", divElement);
var buttonElement = document.getElementsByTagName("button")[0];
buttonElement.style.backgroundColor = "green";
var headingTwoElements = document.getElementsByTagName("h2");
console.log("h2 elements", headingTwoElements);
var shops = document.getElementById("shops");
console.log("shops id", shops);
var items = document.getElementsByClassName("list-item");
console.log("items", items);
var secondItem = items[1];
secondItem.textContent = "Second Element";
console.log("second item", secondItem);
var selectedH2 = document.querySelector("h2");
console.log("selected h2", selectedH2);
